name: Reporte Diario Cripto

on:
  schedule:
    - cron: '0 13 * * *'   # 09:00 Chile
    - cron: '0 17 * * *'   # 13:00 Chile
    - cron: '0 21 * * *'   # 17:00 Chile
    - cron: '0 1  * * *'   # 21:00 Chile
  workflow_dispatch:

jobs:
  enviar-reporte:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests pytz

      - name: Ejecutar reporte
        env:
          TELEFONO:        ${{ secrets.TELEFONO }}
          APIKEY_BOT:      ${{ secrets.APIKEY_BOT }}
          BUDA_API_KEY:    ${{ secrets.BUDA_API_KEY }}
          BUDA_API_SECRET: ${{ secrets.BUDA_API_SECRET }}
        run: python reporte_buda.py
